### ISSUE TITLE
How does one make use of this?

### ISSUE THREAD

**Issue by geoidesic** [clevett/roll20-SheetTemplate#1]
I tried pasting the pug.pug file into the HTML for a custom sheet... but it doesn't read it as HTML... just outputs it all as literal text. Obviously the import at the bottom of the page doesn't work.

I tried searching for a pug script to install but there isn't one in the drop-down list for game API Scripts. So I'm really not sure what to do.

**Comment by Anduh** [comment]
PUG is a template code framework for quicker developing HTML, so you need to install o have access to something that compiles PUG into HTML.

- https://codeburst.io/getting-started-with-pug-template-engine-e49cfa291e33
- https://pugjs.org/api/getting-started.html

**Comment by geoidesic** [comment]
Ok.. I use those in my day job (pug ands css) but they are always compiled by web pack etc. So I'm just not sure how to make use of them within the Roll20 context.

Are you compiling SCSS and PUG locally and then uploading the compiled HTML and CSS to the custom character sheet?

Or is there some other process that's better?

**Comment by Anduh** [comment]
Yeah I'm compiling them locally, installed command line stuff for them.

**Comment by clevett** [comment]
I've actually updated and written a bit in the read me. You'll essentially compile the languages then upload the to a Custom Sheet on Roll20 for testing.
